import { Car } from './types';

export const BYD_CARS: Car[] = [
  {
    id: 'seal',
    name: 'BYD Seal',
    model: 'Performance AWD',
    price: 296800,
    range: 520,
    acceleration: '3.8s',
    image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?q=80&w=1200&auto=format&fit=crop',
    description: 'Um sedan esportivo elétrico de alta performance com design inspirado no oceano e tecnologia CTB (Cell-to-Body).',
    category: 'Sedan',
    features: ['Tração Integral', 'Teto Panorâmico', 'Som Dynaudio', 'NFC Key'],
  },
  {
    id: 'dolphin',
    name: 'BYD Dolphin',
    model: 'EV',
    price: 149800,
    range: 291,
    acceleration: '10.9s',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?q=80&w=1200&auto=format&fit=crop',
    description: 'O hatch elétrico que revolucionou o mercado brasileiro com eficiência, espaço interno surpreendente e design moderno.',
    category: 'Hatch',
    features: ['V2L (Vehicle-to-Load)', 'Tela Giratória 12.8"', 'Câmera 360º', 'Carregamento Celular'],
  },
  {
    id: 'yuan-plus',
    name: 'BYD Yuan Plus',
    model: 'EV',
    price: 229800,
    range: 420,
    acceleration: '7.3s',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=1200&auto=format&fit=crop',
    description: 'Um SUV elétrico dinâmico com interior inspirado em academias e a segurança da Bateria Blade.',
    category: 'SUV',
    features: ['Bateria Blade', 'Rodas 18"', 'ADAS Nível 2', 'Luzes de Ambiente'],
  },
  {
    id: 'song-plus',
    name: 'BYD Song Plus',
    model: 'DM-i Hybrid',
    price: 239800,
    range: 1100,
    acceleration: '8.5s',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=1200&auto=format&fit=crop',
    description: 'O SUV híbrido plug-in que combina o melhor dos dois mundos: economia extrema e autonomia para longas viagens.',
    category: 'SUV',
    features: ['Híbrido Plug-in', 'Porta-malas Elétrico', 'Bancos Ventilados', 'ACC'],
  },
];
